import type { Config } from 'tailwindcss';

// Tokens copied verbatim from desain/neon_protocol/DESIGN.md
export default {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        void: '#050505',
        background: '#131313',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#ffabf3',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#dcbed4',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#a4899d',
        'outline-variant': '#564052',
        primary: '#ffabf3',
        'on-primary': '#5b005b',
        'primary-container': '#ff00ff',
        'on-primary-container': '#510051',
        'inverse-primary': '#a900a9',
        'primary-fixed': '#ffd7f5',
        'primary-fixed-dim': '#ffabf3',
        'on-primary-fixed': '#380038',
        'on-primary-fixed-variant': '#810081',
        secondary: '#ffffff',
        'on-secondary': '#003737',
        'secondary-container': '#00fbfb',
        'on-secondary-container': '#007070',
        'secondary-fixed': '#00fbfb',
        'secondary-fixed-dim': '#00dddd',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        tertiary: '#02e600',
        'on-tertiary': '#013a00',
        'tertiary-container': '#03a900',
        'on-tertiary-container': '#013300',
        'tertiary-fixed': '#77ff61',
        'tertiary-fixed-dim': '#02e600',
        'on-tertiary-fixed': '#002200',
        'on-tertiary-fixed-variant': '#015300',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        danger: '#ff3333',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1440px',
      },
      maxWidth: { 'container-max': '1440px' },
      fontFamily: {
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.1', letterSpacing: '0.15em', fontWeight: '500' }],
      },
    },
  },
} satisfies Config;
